name: Bug Report
description: Report a configuration or deployment issue
title: "[BUG]: "
labels: ["bug"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for taking the time to report an issue! Please provide details below.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component is affected?
      options:
        - Service Configuration
        - Docker Compose
        - OTEL/Observability
        - Documentation
        - CI/CD Pipeline
        - Other
    validations:
      required: true

  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear description of what the bug is
      placeholder: Describe what's happening
    validations:
      required: true

  - type: textarea
    id: steps
    attributes:
      label: Steps to Reproduce
      description: How can we reproduce this issue?
      placeholder: |
        1. Run command '...'
        2. Check service '...'
        3. See error
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What should happen?
      placeholder: Describe expected behavior

  - type: textarea
    id: actual
    attributes:
      label: Actual Behavior
      description: What actually happens?
      placeholder: Describe actual behavior

  - type: textarea
    id: logs
    attributes:
      label: Logs
      description: Relevant log output
      render: shell
      placeholder: Paste logs here

  - type: textarea
    id: environment
    attributes:
      label: Environment
      description: System information
      value: |
        - OS: 
        - Docker Version: 
        - Docker Compose Version: 
        - Branch/Commit: 
      render: markdown

  - type: checkboxes
    id: checks
    attributes:
      label: Pre-submission Checklist
      options:
        - label: I have searched existing issues
          required: true
        - label: I have run `docker-compose config` successfully
          required: false
        - label: I have checked the logs with `docker-compose logs`
          required: false
