services:
  selenium-hub:
    image: selenium/hub:latest
    container_name: selenium-hub
    restart: unless-stopped
    ports:
      - "4444:4444"
    environment:
      - OTEL_EXPORTER_OTLP_ENDPOINT=http://otel-collector:4317
      - OTEL_SERVICE_NAME=selenium-hub
      - OTEL_EXPORTER_OTLP_PROTOCOL=grpc
      - OTEL_METRICS_EXPORTER=otlp
      - OTEL_LOGS_EXPORTER=otlp
      - OTEL_TRACES_EXPORTER=otlp
      - SE_NODE_SESSION_TIMEOUT=300
      - SE_NODE_MAX_SESSIONS=5
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4444/wd/hub/status || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 1G
        reservations:
          cpus: '0.25'
          memory: 256M
    depends_on:
      otel-collector:
        condition: service_healthy
    networks:
      - dev-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  chrome:
    image: selenium/node-chrome:latest
    container_name: selenium-chrome
    restart: unless-stopped
    shm_size: '2gb'
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=3
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    depends_on:
      selenium-hub:
        condition: service_healthy
    networks:
      - dev-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

  firefox:
    image: selenium/node-firefox:latest
    container_name: selenium-firefox
    restart: unless-stopped
    shm_size: '2gb'
    environment:
      - SE_EVENT_BUS_HOST=selenium-hub
      - SE_EVENT_BUS_PUBLISH_PORT=4442
      - SE_EVENT_BUS_SUBSCRIBE_PORT=4443
      - SE_NODE_MAX_SESSIONS=3
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 2G
        reservations:
          cpus: '0.5'
          memory: 1G
    depends_on:
      selenium-hub:
        condition: service_healthy
    networks:
      - dev-net
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"
